permalink: none

url: https://banonotit.github.io/helpdesk/
title: Хелпдеск Школы IT-Решений
description: Сборник статей, туториалов и мануалов

timezone: Europe/Moscow
lang: ru-RU

plugins:
  - jekyll-octicons
  - jekyll-redirect-from

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
sass:
  style: compressed

exclude:
  - local_server.sh
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
